version: "3"

services:
  statistics:
    build: ./statistics
    depends_on:
      - mongo
    deploy:
      replicas: 3
    environment:
      PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
    image: gurkamal/statistics
    ports:
      - 3000:3000
    restart: always

  static:
    build: ./static
    deploy:
      replicas: 3
    image: gurkamal/static
    ports:
      - 8080:8080
    restart: always

  haproxy:
    build: ./haproxy
    depends_on:
      - statistics
      - static
      - mongo
      - dashboard
    deploy:
      replicas: 3
    environment:
      BASE64_AUTH: ${BASE64_AUTH_VALUE}
    image: gurkamal/haproxy
    ports:
      - 5000:80
    restart: always

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    image: mongo:4.2.6-bionic
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /data/db

  dashboard:
    depends_on:
      - mongo
      - statistics
    deploy:
      replicas: 3
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_REQUEST_SIZE: 100kb
      ME_CONFIG_SITE_BASEURL: /dashboard/
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    restart: always
