version: "3"

services:
  # simply here for exec and debug during development
  centos7:
    build: ./centos7

  # placeholder
  dbadmin:
    image: nginxdemos/hello
  # placeholder
  statistics:
    image: nginxdemos/hello

  # static web page
  static:
    build: ./static
    volumes:
      - ./static:/usr/src/app
    ports:
      - 8080:8080

  haproxy:
    build: ./haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 5000:80
  #
  # db:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - 27017:27017
