version: "3"

services:
  statistics:
    build: ./statistics
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./statistics:/usr/src/app

  statistics_test:
    build: ./statistics_test
    depends_on:
      - mongo
    environment:
      PORT: 3001
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./statistics_test:/usr/src/app

  static:
    build: ./static
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./static:/usr/src/app

  haproxy:
    build: ./haproxy
    depends_on:
      - statistics
      - static
      - mongo
      - dbadmin
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    image: mongo:4.2.6-bionic
    ports:
      - 27017:27017
    restart: always

  dbadmin:
    depends_on:
      - mongo
      - statistics
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_REQUEST_SIZE: 100kb
      ME_CONFIG_SITE_BASEURL: /dbadmin/
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    restart: always
