version: "3"

services:
  # simply here for exec and debug during development
  centos7:
    build: ./centos7

  # placeholder
  dbadmin:
    image: nginxdemos/hello
  # placeholder
  statistics:
    image: nginxdemos/hello

  # static web page
  static:
    build: ./static
    volumes:
      - ./static:/usr/src/app
    ports:
      - 8080:8080

  haproxy:
    build: ./haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 5000:80

  db:
    image: mongo:4.2.6-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  dbadmin:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081