version: "3"

services:
  # placeholder
  statistics:
    image: nginxdemos/hello

  static:
    build: ./static
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./static:/usr/src/app

  haproxy:
    build: ./haproxy
    depends_on:
      - statistics
      - static
      - mongo
      - dbadmin
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    image: mongo:4.2.6-bionic
    ports:
      - 27017:27017
    restart: always

  dbadmin:
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_REQUEST_SIZE: 100kb
      ME_CONFIG_SITE_BASEURL: "/dbadmin/"
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    restart: always
