version: "3"

services:
  static-page:
    build: ./static-page
    volumes:
      - ./static-page:/usr/src/app
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
