#!/bin/bash

echo "
################################################################################
# INSTALL NGINX INGRESS CONTROLLER
################################################################################
"

DIRNAME="$(dirname "$(readlink -f "$0")")"
kubectl apply -f "${DIRNAME}/aws-nlb-nginx-ingress-controller.yaml"