#!/bin/bash

################################################################################
# TWEAK CONFIG HERE
################################################################################

# A DNS used for Cluster Name, AWS s3 buckets, and AWS DynamoDB Table
export KUBERNETES_DNS="gurkamalsingh.com"

# Resource location
# Must use odd number of zones (Kops requirement for HA Masters)
export REGION="us-east-1"
export ZONES="us-east-1a,us-east-1b,us-east-1c"

# Kubernetes Node Network topology: [ "public" | "private" ]
export PUBLIC_OR_PRIVATE_NODES="public"

# Master Node Specs
export MASTER_NODE_COUNT="3"
export MASTER_NODE_SIZE="m5.large"
export MASTER_NODE_VOLUME_SIZE_IN_GB="100"

# Worker Node Specs
export WORKER_NODE_COUNT="3"
export WORKER_NODE_SIZE="m5.large"
export WORKER_NODE_VOLUME_SIZE_IN_GB="100"


################################################################################
# Mandatory config vars for Terraform and Kops
################################################################################
# terraform vars
export TF_VAR_s3_bucket_name_kops_state="kops-state-store.${KUBERNETES_DNS}"
# kops setup
export KOPS_CLUSTER_NAME="${KUBERNETES_DNS}"
export KOPS_STATE_STORE="s3://${TF_VAR_s3_bucket_name_terraform_state}"
