#!/bin/bash
echo "
################################################################################
# UNINSTALL NGINX INGRESS CONTROLLER
################################################################################
"
DIRNAME="$(dirname "$(readlink -f "$0")")"
kubectl delete -f "${DIRNAME}/aws-tls-elb-nginx-ingress-controller.yaml"