apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-24T14:19:08Z"
  labels:
    kops.k8s.io/cluster: k8s.dev.gurkamalsingh.com
  name: bastions
spec:
  image: ami-068663a3c619dd892
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-24T14:19:08Z"
  labels:
    kops.k8s.io/cluster: k8s.dev.gurkamalsingh.com
  name: master-us-east-1a
spec:
  associatePublicIp: false
  image: ami-068663a3c619dd892
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 100
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-24T14:19:08Z"
  labels:
    kops.k8s.io/cluster: k8s.dev.gurkamalsingh.com
  name: master-us-east-1b
spec:
  associatePublicIp: false
  image: ami-068663a3c619dd892
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  rootVolumeSize: 100
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-24T14:19:08Z"
  labels:
    kops.k8s.io/cluster: k8s.dev.gurkamalsingh.com
  name: master-us-east-1c
spec:
  associatePublicIp: false
  image: ami-068663a3c619dd892
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  rootVolumeSize: 100
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-24T14:19:08Z"
  labels:
    kops.k8s.io/cluster: k8s.dev.gurkamalsingh.com
  name: nodes
spec:
  associatePublicIp: false
  image: ami-068663a3c619dd892
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
